---
- name: INSTALL | EXTRACT ARCHIVE
  # =====================================================================
  action: unarchive
  args:
      src: "{{cache}}//{{archive_name}}"
      dest: "{{prefix}}/"
      creates: "{{prefix}}/apache-tomcat-{{version}}"

- name: INSTALL | MAKE CONF/ WORLD READABLE
  # =====================================================================
  file:
    path: "{{prefix}}/apache-tomcat-{{version}}/conf"
    mode: "0755"
    recurse: no

