- name: INSTALL | CREATE CATALINA_BASE
  # =====================================================================
  action: file
  args:
    path: "{{catalina_base}}"
    state: "directory"
    mode: "0700"

- name: INSTALL | PREPARE TOMCAT STRUCTURE (DIRECTORIES)
  # =====================================================================
  action: file
  args:
      path: "{{catalina_base}}/{{item}}"
      state: "directory"
  with_items:
      - "bin"
      - "webapps"
      - "work"
      - "temp"
      - "logs"

- name: INSTALL | PREPARE CONTROL SCRIPTS
  # =====================================================================
  template:
  args:
    src: "{{item}}"
    dest: "{{catalina_base}}/{{item}}"
    mode: 0755
  with_items:
      - "bin/startup.sh"
      - "bin/shutdown.sh"
      - "bin/catalina.sh"
      - "bin/setenv.sh"

- name: INSTALL | INSTALL DEFAULT APPLICATIONS
  # =====================================================================
  command: cp -r "{{catalina_home}}/webapps/{{item}}" "{{catalina_base}}/webapps/"
  args:
    creates: "{{catalina_base}}/webapps/{{item}}"
  with_items:
    - "{{manager_apps}}"
