- name: INSTALL | CREATE CATALINA_BASE
  # =====================================================================
  action: file
  args:
    path: "{{catalina_base}}"
    state: "directory"
    mode: "0700"

- name: INSTALL | PREPARE TOMCAT STRUCTURE (DIRECTORIES)
  # =====================================================================
  action: file
  args:
      path: "{{catalina_base}}/{{item}}"
      state: "directory"
  with_items:
      - "bin"
      - "webapps"
      - "work"
      - "temp"
      - "logs"
      - "conf"

- name: INSTALL | PREPARE TOMCAT STRUCTURE (COPY)
  # =====================================================================
  command: cp "{{catalina_home}}/{{item}}" "{{catalina_base}}/{{item}}"
  args:
    creates: "{{catalina_base}}/{{item}}"
  # action: copy
  # args:
  #     dest: "{{catalina_home}}/{{item}}"
  #     src: "{{catalina_home}}/apache-tomcat-{{apache_tomcat_download_version}}/{{item}}"
  #     remote_src: True
  with_items:
      - "conf/catalina.policy"
      - "conf/catalina.properties"
      - "conf/context.xml"
      - "conf/logging.properties"
      - "conf/server.xml"
      - "conf/tomcat-users.xml"
      - "conf/web.xml"

- name: INSTALL | PREPARE CONTROL SCRIPTS AND CONFIGURATION
  # =====================================================================
  template:
  args:
    src: "{{item}}"
    dest: "{{catalina_base}}/{{item}}"
    mode: 0755
  with_items:
      - "bin/startup.sh"
      - "bin/shutdown.sh"
      - "bin/catalina.sh"
      - "bin/setenv.sh"
      - "conf/server.xml"

- name: INSTALL | PREPARE TOMCAT STRUCTURE (MANAGER APPS)
  # =====================================================================
  command: cp -r "{{catalina_home}}/webapps/{{item}}" "{{catalina_base}}/webapps/"
  args:
    creates: "{{catalina_base}}/webapps/{{item}}"
  with_items:
    - "{{manager_apps}}"
