---
- name: DOWNLOAD | CREATE DOWNLOAD CACHE DIRECTORY
  # ===============================================================================
  sudo: no
  delegate_to: 127.0.0.1
  action: file
  args:
    state: "directory"
    path: "{{cache}}"

- name: DOWNLOAD | FETCH ARTIFACT
  # =====================================================================
  action: get_url
  sudo: false
  delegate_to: 127.0.0.1
  args:
      url:  "{{download_url}}"
      dest: "{{cache}}/{{archive_name}}"
      # :TODO: Ansible 2.0 - Enable
      # checksum: "{{tomcat_checksum}}"

