---
- name: "INIT | CHECK PARAMETERS"
  # =========================================================================
  assert:
    that:
      # (localhost) where to cache the tomcat archive.
      - cache_directory is defined and cache_directory is not none
      # We need a TOMCAT_HOME to install jenkins into ($TOMCAT_HOME/webapps)
      - catalina_base is defined and catalina_base is not none
      # jenkins version to download and install
      - version is defined and version is not none
      # We should set up a JENKINS_HOME outside of ~/.jenkins (the default).
      - jenkins_home is defined and jenkins_home is not none
