---
- name: DOWNLOAD | CREATE DOWNLOAD CACHE DIRECTORY
  # =====================================================================
  sudo: No
  delegate_to: 127.0.0.1
  action: file
  args:
    path: "{{cache}}/"
    state: "directory"

- name: DOWNLOAD | FETCH ARTIFACT
  # =====================================================================
  sudo: No
  delegate_to: 127.0.0.1
  action: get_url
  args:
      url:  "{{download_url}}"
      dest: "{{cache}}/jenkins-{{version}}.war"

