---
- name: DOWNLOAD | CREATE CACHE DIRECTORY
  # =====================================================================
  sudo: No
  delegate_to: 127.0.0.1
  action: file
  args:
    path: "{{download_cache}}/jenkins/jenkins-core"
    state: "directory"

- name: DOWNLOAD | CORE
  # =====================================================================
  sudo: No
  delegate_to: 127.0.0.1
  action: get_url
  args:
      url:  "{{jenkins_download_url}}"
      dest: "{{download_cache}}/jenkins/jenkins-core/jenkins-{{jenkins_version}}.war"

