- name: "CONFIGURE | AUTHENTICATION STRATEGY"
 # =====================================================================
  action: template
  args:
    src: "authentication/{{authentication_strategy}}.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/00_authentication_strategy.groovy"

- name: "CONFIGURE | AUTHORIZATION STRATEGY"
 # =====================================================================
  action: template
  args:
    src: "authorization/{{authorization_strategy}}.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/20_authorization_strategy.groovy"

- name: "CONFIGURE | LOCATION PROPERTIES"
 # =====================================================================
  action: template
  args:
    src: "init.groovy.d/configure-location-properties.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/30_configure-location-properties.groovy"
  when: admin_email is defined or url is defined

- name: "CONFIGURE | EMAIL NOTIFICATION"
 # =====================================================================
  action: template
  args:
    src: "init.groovy.d/configure-email-notification.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/30_configure-email-notification.groovy"
  when: smtp_host is defined

- name: "CONFIGURE | USERS"
 # =====================================================================
  action: template
  args:
    src: "init.groovy.d/configure_users.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/30_configure_users.groovy"
- name: "CONFIGURE | BOOTSTRAP JOB"
 # =====================================================================
  action: template
  args:
    src: "bootstrap/bootstrap.job"
    dest: "{{jenkins_home}}/init.groovy.d/80_configure-bootstrap-job.groovy"
  when: bootstrap_git_repo is defined
