---

- name: DOWNLOAD | CREATE DOWNLOAD CACHE DIRECTORY
  # =====================================================================
  action: file
  sudo: false
  delegate_to: 127.0.0.1
  args:
    path: "{{download_cache}}/tomcat-8/tomcat-core"
    state: "directory"

- name: DOWNLOAD | ARCHIVE
  # =====================================================================
  action: get_url
  sudo: false
  delegate_to: 127.0.0.1
  args:
      url:  "{{apache_tomcat_download_url}}"
      dest: "{{download_cache}}/tomcat-8/tomcat-core/{{apache_tomcat_download_archive_name}}"
      # :TODO: Ansible 2.0 - Enable
      # checksum: "{{tomcat_checksum}}"
  register:
      apache_tomcat_download_changed

