---
- name: INSTALL | EXTRACT ARCHIVE
  # =====================================================================
  action: unarchive
  args:
      src: "{{download_cache}}/tomcat-8/tomcat-core/{{apache_tomcat_download_archive_name}}"
      dest: "{{apache_tomcat_prefix}}/"
      creates: "{{apache_tomcat_prefix}}/apache-tomcat-{{tomcat_version}}"
