- name: "CONFIGURE | AUTHENTICATION STRATEGY"
 # =====================================================================
  action: template
  args:
    src: "authentication/{{authentication_strategy}}.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/00_authentication_strategy.groovy"

- name: "CONFIGURE | AUTHORIZATION STRATEGY"
 # =====================================================================
  action: template
  args:
    src: "authorization/{{authorization_strategy}}.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/20_authorization_strategy.groovy"

- name: "CONFIGURE | LOCATION PROPERTIES"
 # =====================================================================
  action: template
  args:
    src: "init.groovy.d/configure-location-properties.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/40_configure-location-properties.groovy"

- name: "CONFIGURE | USERS"
 # =====================================================================
  action: template
  args:
    src: "init.groovy.d/configure_users.groovy"
    dest: "{{jenkins_home}}/init.groovy.d/60_configure_users.groovy"

