---
- name: CHECK | PARAMETERS
  # =========================================================================
  assert:
    that:
      # The java version number to install (eg. 1.8.0_65)
      - version and version | match("[0-9]+\.[0-9]+\.[0-9]+_[0-9]+")
      # The build number corresponding to the version-
      - build
      # The platform to download.
      - platform
      # The format to download.
      - format and format in ('tar.gz', 'Z')
      # Local download cache directory
      - cache_directory

