---

- name: DOWNLOAD | CREATE DOWNLOAD CACHE DIRECTORY
  # ===============================================================================
  sudo: no
  delegate_to: 127.0.0.1
  action: file
  args:
    state: "directory"
    path: "{{cache}}"

- name: DOWNLOAD | FETCH ARTIFACT
  # ===============================================================================
  sudo: no
  delegate_to: 127.0.0.1
  command: wget --no-check-certificate --no-cookies --header "Cookie{{':'}} oraclelicense=accept-securebackup-cookie" {{url}}
  args:
      chdir: "{{cache}}"
      creates: "{{artifact}}"

