---
- name: DOWNLOAD | CREATE DOWNLOAD CACHE DIRECTORY
  # ===============================================================================
  sudo: no
  delegate_to: 127.0.0.1
  action: file
  args:
    state: "directory"
    path: "{{cache}}"

- name: DOWNLOAD | FETCH ARTIFACT
  # ===============================================================================
  sudo: no
  delegate_to: 127.0.0.1
  get_url:
    url: "{{download_url}}"
    dest: "{{cache}}/{{artifact}}"
