---
- assert:
    that:
      # if smtp_host is set assure a email adress is given.
      - smtp_host is none or smtp_replyto is not none
      # If a username is given we need a password too
      - smtp_username is none or smtp_password is not none
      # Make sure jenkins_home is set
      - jenkins_home is not none
